[project]
name = "cse291a"
version = "0.1.0"
description = "CSE 291A @ UCSD, Fall 2025"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "ollama>=0.6.0",
    "pdfplumber>=0.11.7",
    "qdrant-client[fastembed]>=1.14.1",
]
